on:
  push:
  pull_request:

jobs:
  build:
    permissions:
      contents: write
    strategy:
      matrix:
        include:
          - name: darwin-aarch64
            platform: macos-latest
            target: aarch64-apple-darwin
          - name: darwin-x86_64
            platform: macos-latest
            target: x86_64-apple-darwin
          - name: linux-x86_64
            platform: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - name: windows-x86_64
            platform: windows-latest
            target: x86_64-pc-windows-msvc
            suffix: .exe

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Rust toolchain for ${{ matrix.target }}
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: (Ubuntu) Install native dependencies
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y \
            libudev-dev

      - name: Set up temperary SSH key to fetch cskburn-rs
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_CSKBURN }}

      - name: Build
        run: cargo build --release --target ${{ matrix.target }}
        env:
          CARGO_NET_GIT_FETCH_WITH_CLI: true

      - name: Archive distributable
        uses: actions/upload-artifact@v4
        with:
          name: commands-mcp_${{ github.run_id }}_${{ matrix.name }}
          path: target/${{ matrix.target }}/release/commands-mcp${{ matrix.suffix }}
