on:
  push:
    branches:
      - master
      - v*

permissions:
  contents: write
  id-token: write
  pages: write

jobs:
  schema:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Generate schema
        run: npm run build-schema

      - name: Checkout schema branch
        uses: actions/checkout@v4
        with:
          ref: schema
          path: schema
          fetch-depth: 0

      - name: Commit and push schema
        run: |
          cp dist/schema.json schema/${{ github.ref_name }}.json
          cd schema
          git config user.name "xychen"
          git config user.email "xychen@listenai.com"
          if [[ -z "$(git status --porcelain)" ]]; then
            echo "No changes to commit"
          else
            git add ${{ github.ref_name }}.json
            git commit -m "Update schema for ${{ github.ref_name }}"
            git push
          fi

  pack:
    runs-on: ubuntu-latest
    needs: schema

    steps:
      - name: Checkout schema
        uses: actions/checkout@v4
        with:
          ref: schema
          path: schema

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ github.workspace }}

  deploy:
    runs-on: ubuntu-latest
    needs: pack

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
